TASKS = [
    ("1.algorithm", "1-1.algorithm", "Design, implement, and optimize core algorithmic solutions for complex computational problems. This includes conducting thorough algorithm analysis, selecting appropriate data structures, implementing efficient algorithms with optimal time and space complexity, and performing comprehensive performance benchmarking. Responsibilities encompass researching existing algorithmic approaches, developing novel solutions when needed, analyzing computational complexity using Big O notation, implementing unit tests for algorithm validation, documenting algorithm logic and trade-offs, and collaborating with other teams to integrate algorithmic components into larger systems. The role requires proficiency in mathematical modeling, algorithm design patterns, and optimization techniques to ensure scalable and maintainable solutions."),

    ("2.application_development", "2-1.application_development", "Lead the overall application development lifecycle from conception to deployment, serving as the central coordinator for all development activities. This involves establishing development standards and coding conventions, designing application architecture and system blueprints, managing cross-functional development teams, conducting code reviews and quality assurance processes, and ensuring adherence to software engineering best practices. Key responsibilities include requirement analysis and technical specification creation, technology stack selection and evaluation, project timeline management and milestone tracking, risk assessment and mitigation planning, stakeholder communication and progress reporting, and maintaining comprehensive documentation throughout the development process. The role demands strong leadership skills, technical expertise across multiple domains, and the ability to balance technical debt with feature delivery."),
    
    ("2.application_development", "2-2.llm_development", "Specialize in the end-to-end development and optimization of Large Language Models, encompassing model architecture design, training pipeline development, and inference optimization. Core responsibilities include designing transformer-based architectures and novel model components, implementing distributed training systems for large-scale model training, developing data preprocessing pipelines for text tokenization and dataset preparation, fine-tuning pre-trained models for specific tasks and domains, optimizing model inference speed and memory usage, implementing evaluation metrics and benchmarking frameworks, and staying current with cutting-edge research in natural language processing. Additional tasks involve hyperparameter tuning and experimentation, model compression and quantization techniques, deployment of models in production environments, monitoring model performance and drift detection, and collaborating with researchers to implement state-of-the-art techniques."),
    
    ("2.application_development", "2-3.backend_development", "Build and maintain robust, scalable server-side applications and services that form the backbone of the system. This encompasses designing and implementing RESTful APIs and GraphQL endpoints, developing microservices architecture with proper service decomposition, implementing database design and optimization strategies, creating authentication and authorization systems, and establishing comprehensive logging and monitoring solutions. Key responsibilities include developing business logic and data processing workflows, implementing caching strategies for performance optimization, ensuring data integrity and transaction management, creating automated testing suites for backend components, managing third-party integrations and external API communications, implementing security best practices including input validation and SQL injection prevention, and optimizing database queries and connection pooling. The role requires expertise in server-side technologies, database management, and distributed systems design."),
    
    ("2.application_development", "2-4.ui_optimization", "Focus on enhancing user interface performance, visual appeal, and overall user experience through systematic optimization techniques. This involves conducting user experience audits and usability testing, implementing responsive design principles for cross-device compatibility, optimizing rendering performance and reducing layout shifts, creating smooth animations and micro-interactions, and ensuring accessibility compliance with WCAG guidelines. Core responsibilities include analyzing user behavior patterns and interaction flows, implementing performance monitoring and metrics collection, optimizing asset loading and bundle sizes, conducting A/B testing for interface improvements, creating design systems and component libraries, optimizing for search engine visibility and core web vitals, and collaborating with UX designers to implement pixel-perfect designs. The role requires deep understanding of CSS optimization, JavaScript performance, browser rendering engines, and modern frontend optimization tools."),
    
    ("2.application_development", "2-5.frontend_development", "Develop dynamic, interactive user interfaces and client-side applications that provide exceptional user experiences across multiple platforms and devices. This includes implementing modern frontend frameworks and libraries, managing application state and data flow, creating reusable component architectures, and integrating with backend APIs and services. Key responsibilities encompass developing responsive web applications with mobile-first design principles, implementing client-side routing and navigation systems, managing form validation and user input handling, optimizing frontend performance and bundle optimization, implementing progressive web app features, creating comprehensive testing strategies including unit and integration tests, and ensuring cross-browser compatibility and graceful degradation. Additional tasks involve implementing real-time features using WebSockets or Server-Sent Events, managing client-side caching and offline functionality, and collaborating with designers to translate mockups into functional interfaces."),
    
    ("2.application_development", "2-6.build_deployment", "Establish and maintain comprehensive CI/CD pipelines and deployment infrastructure to ensure reliable, automated, and efficient software delivery processes. This involves designing build automation workflows, configuring containerization with Docker and orchestration systems, implementing infrastructure as code using tools like Terraform or CloudFormation, and managing multi-environment deployment strategies. Core responsibilities include setting up automated testing pipelines with quality gates, implementing blue-green and canary deployment strategies, monitoring deployment health and rollback procedures, managing secrets and environment configuration, establishing logging and monitoring infrastructure, optimizing build times and resource utilization, and ensuring security scanning and compliance checks. The role requires expertise in cloud platforms, containerization technologies, monitoring tools, and DevOps best practices to maintain high availability and seamless deployment experiences."),
    
    ("3.research", "3-1.research", "Conduct comprehensive technical research and innovation initiatives to identify emerging technologies, evaluate their potential impact, and guide strategic technical decisions. This involves performing literature reviews and staying current with academic publications, analyzing industry trends and competitive landscapes, conducting proof-of-concept implementations and feasibility studies, and evaluating new tools, frameworks, and methodologies. Key responsibilities include designing and executing controlled experiments to validate hypotheses, creating detailed technical reports and recommendations, collaborating with academic institutions and research communities, attending conferences and technical symposiums, maintaining knowledge bases and research documentation, and translating research findings into actionable insights for development teams. The role requires strong analytical skills, scientific methodology expertise, and the ability to bridge theoretical concepts with practical applications."),

    ("4.data/file_analysis/processing", "4-1.data/file_analysis/processing", "Design and implement comprehensive data processing pipelines and analytical frameworks to extract insights from large-scale datasets and various file formats. This encompasses developing ETL (Extract, Transform, Load) processes, implementing data validation and quality assurance mechanisms, creating statistical analysis and machine learning models, and building automated reporting systems. Core responsibilities include designing data schemas and database optimization strategies, implementing real-time and batch data processing workflows, creating data visualization dashboards and interactive reports, managing data privacy and compliance requirements, developing data lineage and governance frameworks, optimizing data storage and retrieval performance, and ensuring data accuracy and consistency across multiple sources. Additional tasks involve implementing data monitoring and alerting systems, creating APIs for data access, and collaborating with stakeholders to define analytical requirements and KPIs."),

    ("5.codebase-resolve-issues/debugging", "5-1.codebase-resolve-issues/debugging", "Systematically identify, analyze, and resolve complex technical issues within the codebase while improving overall code quality and system reliability. This involves implementing comprehensive debugging strategies, performing root cause analysis for production incidents, conducting code reviews and static analysis, and establishing preventive measures to minimize future issues. Key responsibilities include developing debugging tools and utilities, creating and maintaining troubleshooting documentation, implementing logging and monitoring solutions for issue detection, performing performance profiling and optimization, refactoring legacy code and technical debt reduction, establishing coding standards and best practices, and mentoring team members on debugging techniques. The role requires expertise in multiple programming languages, debugging tools, performance analysis, and the ability to work under pressure during critical production incidents while maintaining code quality standards.")
]


GENERATION_TASKS = """
# PR to Task Extraction Prompt

You are an expert software development analyst tasked with converting Pull Request (PR) data into specific, actionable development tasks for testing AI agents' coding capabilities.

## Input 1: PR Complete Description
```
{PR_DATA}
```

## Input 2: Available Task Categories

### 1-1. Algorithm
**Description**: Design, implement, and optimize core algorithmic solutions for complex computational problems. This includes conducting thorough algorithm analysis, selecting appropriate data structures, implementing efficient algorithms with optimal time and space complexity, and performing comprehensive performance benchmarking. Responsibilities encompass researching existing algorithmic approaches, developing novel solutions when needed, analyzing computational complexity using Big O notation, implementing unit tests for algorithm validation, documenting algorithm logic and trade-offs, and collaborating with other teams to integrate algorithmic components into larger systems. The role requires proficiency in mathematical modeling, algorithm design patterns, and optimization techniques to ensure scalable and maintainable solutions.

### 2-1. Application Development
**Description**: Lead the overall application development lifecycle from conception to deployment, serving as the central coordinator for all development activities. This involves establishing development standards and coding conventions, designing application architecture and system blueprints, managing cross-functional development teams, conducting code reviews and quality assurance processes, and ensuring adherence to software engineering best practices. Key responsibilities include requirement analysis and technical specification creation, technology stack selection and evaluation, project timeline management and milestone tracking, risk assessment and mitigation planning, stakeholder communication and progress reporting, and maintaining comprehensive documentation throughout the development process. The role demands strong leadership skills, technical expertise across multiple domains, and the ability to balance technical debt with feature delivery.

### 2-2. LLM Development
**Description**: Specialize in the end-to-end development and optimization of Large Language Models, encompassing model architecture design, training pipeline development, and inference optimization. Core responsibilities include designing transformer-based architectures and novel model components, implementing distributed training systems for large-scale model training, developing data preprocessing pipelines for text tokenization and dataset preparation, fine-tuning pre-trained models for specific tasks and domains, optimizing model inference speed and memory usage, implementing evaluation metrics and benchmarking frameworks, and staying current with cutting-edge research in natural language processing. Additional tasks involve hyperparameter tuning and experimentation, model compression and quantization techniques, deployment of models in production environments, monitoring model performance and drift detection, and collaborating with researchers to implement state-of-the-art techniques.

### 2-3. Backend Development
**Description**: Build and maintain robust, scalable server-side applications and services that form the backbone of the system. This encompasses designing and implementing RESTful APIs and GraphQL endpoints, developing microservices architecture with proper service decomposition, implementing database design and optimization strategies, creating authentication and authorization systems, and establishing comprehensive logging and monitoring solutions. Key responsibilities include developing business logic and data processing workflows, implementing caching strategies for performance optimization, ensuring data integrity and transaction management, creating automated testing suites for backend components, managing third-party integrations and external API communications, implementing security best practices including input validation and SQL injection prevention, and optimizing database queries and connection pooling. The role requires expertise in server-side technologies, database management, and distributed systems design.

### 2-4. UI Optimization
**Description**: Focus on enhancing user interface performance, visual appeal, and overall user experience through systematic optimization techniques. This involves conducting user experience audits and usability testing, implementing responsive design principles for cross-device compatibility, optimizing rendering performance and reducing layout shifts, creating smooth animations and micro-interactions, and ensuring accessibility compliance with WCAG guidelines. Core responsibilities include analyzing user behavior patterns and interaction flows, implementing performance monitoring and metrics collection, optimizing asset loading and bundle sizes, conducting A/B testing for interface improvements, creating design systems and component libraries, optimizing for search engine visibility and core web vitals, and collaborating with UX designers to implement pixel-perfect designs. The role requires deep understanding of CSS optimization, JavaScript performance, browser rendering engines, and modern frontend optimization tools.

### 2-5. Frontend Development
**Description**: Develop dynamic, interactive user interfaces and client-side applications that provide exceptional user experiences across multiple platforms and devices. This includes implementing modern frontend frameworks and libraries, managing application state and data flow, creating reusable component architectures, and integrating with backend APIs and services. Key responsibilities encompass developing responsive web applications with mobile-first design principles, implementing client-side routing and navigation systems, managing form validation and user input handling, optimizing frontend performance and bundle optimization, implementing progressive web app features, creating comprehensive testing strategies including unit and integration tests, and ensuring cross-browser compatibility and graceful degradation. Additional tasks involve implementing real-time features using WebSockets or Server-Sent Events, managing client-side caching and offline functionality, and collaborating with designers to translate mockups into functional interfaces.

### 2-6. Build Deployment
**Description**: Establish and maintain comprehensive CI/CD pipelines and deployment infrastructure to ensure reliable, automated, and efficient software delivery processes. This involves designing build automation workflows, configuring containerization with Docker and orchestration systems, implementing infrastructure as code using tools like Terraform or CloudFormation, and managing multi-environment deployment strategies. Core responsibilities include setting up automated testing pipelines with quality gates, implementing blue-green and canary deployment strategies, monitoring deployment health and rollback procedures, managing secrets and environment configuration, establishing logging and monitoring infrastructure, optimizing build times and resource utilization, and ensuring security scanning and compliance checks. The role requires expertise in cloud platforms, containerization technologies, monitoring tools, and DevOps best practices to maintain high availability and seamless deployment experiences.

### 3-1. Research
**Description**: Conduct comprehensive technical research and innovation initiatives to identify emerging technologies, evaluate their potential impact, and guide strategic technical decisions. This involves performing literature reviews and staying current with academic publications, analyzing industry trends and competitive landscapes, conducting proof-of-concept implementations and feasibility studies, and evaluating new tools, frameworks, and methodologies. Key responsibilities include designing and executing controlled experiments to validate hypotheses, creating detailed technical reports and recommendations, collaborating with academic institutions and research communities, attending conferences and technical symposiums, maintaining knowledge bases and research documentation, and translating research findings into actionable insights for development teams. The role requires strong analytical skills, scientific methodology expertise, and the ability to bridge theoretical concepts with practical applications.

### 4-1. Data/File Analysis/Processing
**Description**: Design and implement comprehensive data processing pipelines and analytical frameworks to extract insights from large-scale datasets and various file formats. This encompasses developing ETL (Extract, Transform, Load) processes, implementing data validation and quality assurance mechanisms, creating statistical analysis and machine learning models, and building automated reporting systems. Core responsibilities include designing data schemas and database optimization strategies, implementing real-time and batch data processing workflows, creating data visualization dashboards and interactive reports, managing data privacy and compliance requirements, developing data lineage and governance frameworks, optimizing data storage and retrieval performance, and ensuring data accuracy and consistency across multiple sources. Additional tasks involve implementing data monitoring and alerting systems, creating APIs for data access, and collaborating with stakeholders to define analytical requirements and KPIs.

### 5-1. Codebase Resolve Issues/Debugging
**Description**: Systematically identify, analyze, and resolve complex technical issues within the codebase while improving overall code quality and system reliability. This involves implementing comprehensive debugging strategies, performing root cause analysis for production incidents, conducting code reviews and static analysis, and establishing preventive measures to minimize future issues. Key responsibilities include developing debugging tools and utilities, creating and maintaining troubleshooting documentation, implementing logging and monitoring solutions for issue detection, performing performance profiling and optimization, refactoring legacy code and technical debt reduction, establishing coding standards and best practices, and mentoring team members on debugging techniques. The role requires expertise in multiple programming languages, debugging tools, performance analysis, and the ability to work under pressure during critical production incidents while maintaining code quality standards.

## Instructions

1. **Analyze the PR**: Carefully examine the PR data including title, description, file changes, commits, and any discussion context.

2. **Identify Primary Task**: Determine which single task category (from the list above) best represents the core technical work required by this PR. Consider:
   - The main technical challenge or implementation requirement
   - The primary skill set needed to complete the work
   - The type of code changes being made

3. **Extract Key Information**: From the PR data, identify:
   - Repository ID and PR number
   - Files that need to be modified (changed in the PR)
   - Related files that provide context (mentioned or relevant to understanding)
   - The specific technical requirements and implementation details

4. **Generate Test Query**: Create a clear, specific query that an AI agent could receive to implement this task. The query should:
   - Be written as if from a developer requesting help
   - Include specific technical requirements
   - Mention key technologies, frameworks, or patterns involved
   - Be concrete enough to have a testable outcome

## Output Requirements

Provide your analysis in the following JSON format:

```json
{{
  "test_query": "A clear, specific query that describes what needs to be implemented, as if a developer is asking an AI agent for help. Should include technical requirements, expected behavior, and key implementation details.",
  "repo_id": "<repository_id_from_pr_data>",
  "pr_id": "<pr_number_from_pr_data>", 
  "task_category": "<selected_task_id_and_name>",
  "modified_files": [
    "file1.ext",
    "file2.ext"
  ],
  "related_files": [
    "related_file1.ext", 
    "related_file2.ext"
  ],
  "reasoning": "Brief explanation of why you selected this task category and how you identified the key files and requirements."
}}
```

## Important Notes

- Focus on the **primary technical challenge** - don't try to capture every minor aspect of the PR
- The test_query should be **specific and actionable** - an AI agent should be able to implement a solution based on this query alone
- Include only files that are directly **modified** in modified_files, and files that provide **necessary context** in related_files
- The task_category should be the **single best match** from the provided list
- Keep the reasoning **concise but informative**

Now, analyze the provided PR data and generate the task extraction.
"""